# -*- coding: utf-8 -*-
"""Render the authored measure core: KPIs, metrics, KRIs, note OKRs, OMTM cards, dashboard specs.

    python chart-expert/scripts/build_measures.py            # write
    python chart-expert/scripts/build_measures.py --check    # exit 1 if anything would change

Everything here is written from the constants in this file. No external source is
read. The Compendium-scale catalogue (tens of thousands of extracted KPI names)
is licensed material and is built in the private dashboard-library repository;
it is not part of this public library.

Owned outputs (regenerated in full; do not edit by hand):
- library/KPIS/_catalog/kpis.jsonl, library/KPIS/_catalog/metrics.jsonl
- library/KPIS/index.md and one page per function
- library/KRIS/index.md
- library/OKRS/index.md and library/OKRS/note/*.md
- library/OMTM/index.md and one card per business model
- library/DASHBOARDS/index.md, one spec per (function, area), patterns/*.md
- the related_kpis line of every chart card
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parent
LIB = ROOT / "library"
CHARTS = LIB / "CHARTS"
GENERATED = "Generated by `chart-expert/scripts/build_measures.py`. Do not edit by hand."

UNITS = {"currency", "percent", "count", "number", "days", "hours", "months"}
DIRECTIONS = {"up", "down", "corridor"}
# Reader roles. Each maps to one chart-audience tolerance (references/retrieval-dimensions.md).
ROLE_TOLERANCE = {
    "Executive": "Executive",
    "Client": "Executive",
    "HR business partner": "Executive",
    "Marketing lead": "Executive",
    "Marketing analytics": "Analytics",
    "Data analytics": "Analytics",
    "Data scientist": "Technical",
    "Researcher": "Technical",
    "R&D": "Technical",
    "Development": "Technical",
    "Public": "Public",
}
ROLES_BY_FUNCTION = {
    "Finance": ["Executive", "Data analytics"],
    "Human Resources": ["HR business partner", "Data analytics"],
    "Information Technology": ["Development", "Data analytics"],
    "Management": ["Executive", "Researcher"],
    "Marketing and Communications": ["Marketing lead", "Marketing analytics"],
    "Online Presence": ["Marketing lead", "Marketing analytics"],
    "Portfolio and Project Management": ["Executive", "Client", "Data analytics"],
    "Professional Services": ["Executive", "Client", "Data analytics"],
    "Sales and Customer Service": ["Executive", "Data analytics"],
}


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower().replace("&", " and ")).strip("-")


@dataclass
class M:
    name: str
    function: str
    area: str
    unit: str
    formula: str
    inputs: list[str]
    direction: str
    timing: str
    definition: str
    kind: str = "kpi"
    charts: tuple[str, str] | None = None  # (communication, analysis) override
    extra_charts: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)


GP_HEAD = ("Published agency rule of thumb, not a law: about 135,000 AUD, 75,000 GBP, or 95,000 USD gross profit "
           "per fee earner per year (about 20,000 AUD, 10,000 GBP, or 13,000 USD per month).")
CORE: list[M] = [
    # Finance
    M("Days sales outstanding", "Finance", "Cash Management", "days", "(A / B) * C", ["accounts receivable", "credit sales", "days in period"], "down", "lagging",
      "Average days to collect credit sales: receivables divided by credit sales over the period, times the days in the period."),
    M("Accounts receivable aging", "Finance", "Cash Management", "currency", "A", ["receivables grouped by age bucket"], "down", "lagging",
      "Receivables split by how long they have been outstanding. The amount past the agreed terms is the exposure.", kind="kri",
      charts=("stacked-bar-chart", "histogram")),
    M("Operating cash flow", "Finance", "Cash Management", "currency", "A", ["cash from operations"], "up", "lagging",
      "Cash generated by operations in the period."),
    M("Revenue per employee", "Finance", "Profitability", "currency", "A / B", ["revenue", "employees"], "up", "lagging",
      "Revenue divided by average headcount in the period."),
    M("Net revenue minus CAC", "Finance", "Profitability", "currency", "A - B", ["net revenue", "customer acquisition cost"], "up", "lagging",
      "Net revenue left after acquisition cost."),
    M("Profit margin", "Finance", "Profitability", "percent", "(A / B) * 100", ["profit", "revenue"], "up", "lagging",
      "Profit divided by revenue. The name on the page must say which profit (gross, operating, net)."),
    M("Gross profit margin", "Finance", "Profitability", "percent", "(A / B) * 100", ["gross profit", "revenue"], "up", "lagging",
      "Share of revenue left after direct cost."),
    M("LTV to CAC ratio", "Finance", "Profitability", "number", "A / B", ["customer lifetime value", "customer acquisition cost"], "up", "lagging",
      "How many times acquisition cost is covered by lifetime value."),
    M("Net profit", "Finance", "Profitability", "currency", "A - B", ["revenue", "total costs"], "up", "lagging",
      "What remains of revenue after all costs."),
    M("Monthly recurring profit", "Finance", "Profitability", "currency", "A", ["recurring profit for the month"], "up", "lagging",
      "Recurring profit normalized to one month."),
    M("Days to close", "Finance", "Close", "days", "A", ["business days from period end to close"], "down", "lagging",
      "Business days from period end until the books are closed."),
    M("Budgets reviewed", "Finance", "Planning", "count", "A", ["function budgets reviewed"], "up", "leading",
      "Function budgets reviewed against the request. A process count, not the financial outcome."),
    # Human Resources
    M("Employee pulse score", "Human Resources", "Engagement", "number", "A", ["mean pulse response"], "up", "leading",
      "Mean response on the stated pulse scale."),
    M("Town hall held", "Human Resources", "Engagement", "count", "A", ["town halls held"], "up", "leading",
      "Count of town halls held. A task count; the outcome is the pulse or retention that follows."),
    M("Account executives hired", "Human Resources", "Hiring", "count", "A", ["account executives who started"], "up", "lagging",
      "Account executives who started in the period."),
    M("Sales development hires", "Human Resources", "Hiring", "count", "A", ["sales development representatives who started"], "up", "lagging",
      "Sales development hires who started in the period."),
    M("Interview to offer ratio", "Human Resources", "Hiring", "number", "A / B", ["interviews", "offers"], "corridor", "leading",
      "Interviews divided by offers. A corridor: too low and too high both mean the process is off."),
    M("SDRs trained", "Human Resources", "Hiring", "count", "A", ["sales development representatives who finished training"], "up", "leading",
      "Sales development representatives who finished the named training."),
    # Information Technology
    M("Unplanned downtime", "Information Technology", "Reliability", "hours", "A", ["unplanned downtime duration"], "down", "lagging",
      "Duration of unplanned unavailability in the period.", kind="kri", charts=("run-chart", "histogram")),
    M("Restore tests passed", "Information Technology", "Reliability", "count", "A", ["restore tests passed"], "up", "leading",
      "Backup restore tests that passed the agreed check."),
    M("Critical defects", "Information Technology", "Quality", "count", "A", ["critical defects found after release"], "down", "lagging",
      "Critical defects found after the release, on the stated severity rule.", kind="kri", charts=("run-chart", "bar-chart")),
    M("Regressions", "Information Technology", "Quality", "count", "A", ["regressions found after release"], "down", "lagging",
      "Behaviors that worked before the release and failed after it.", kind="kri", charts=("run-chart", "bar-chart")),
    # Management
    M("Usability score", "Management", "Discovery", "number", "A", ["mean usability score"], "up", "leading",
      "Mean score on the stated usability scale for the prototype or release."),
    # Marketing and Communications
    M("Customer acquisition cost", "Marketing and Communications", "Acquisition", "currency", "A / B", ["sales and marketing cost", "new customers acquired"], "down", "lagging",
      "Sales and marketing cost to acquire one new customer. Cost per acquisition is the same measure when the unit acquired is a customer."),
    M("Cost per lead", "Marketing and Communications", "Acquisition", "currency", "A / B", ["campaign cost", "leads"], "down", "lagging",
      "Campaign spend divided by leads."),
    M("Click through rate", "Marketing and Communications", "Acquisition", "percent", "(A / B) * 100", ["clicks", "impressions"], "up", "leading",
      "Clicks divided by impressions."),
    M("Marketing qualified leads", "Marketing and Communications", "Acquisition", "count", "A", ["leads meeting the qualification rule"], "up", "leading",
      "Leads that meet the written qualification rule. Say the channel when the result is channel-specific."),
    M("Wins by lead source", "Marketing and Communications", "Acquisition", "count", "A", ["wins coded to a lead source"], "up", "lagging",
      "Closed work split by the source of the lead.", charts=("horizontal-bar-chart", "bar-chart")),
    M("Analyst briefings", "Marketing and Communications", "Awareness", "count", "A", ["analyst briefings held"], "up", "leading",
      "Briefings held with analysts."),
    M("Analyst webinars", "Marketing and Communications", "Awareness", "count", "A", ["webinars with an analyst"], "up", "leading",
      "Webinars that included an analyst."),
    M("Influencer meetings", "Marketing and Communications", "Awareness", "count", "A", ["influencer meetings held"], "up", "leading",
      "Meetings held with influencers."),
    M("Media meetings", "Marketing and Communications", "Awareness", "count", "A", ["media meetings held"], "up", "leading",
      "Meetings held with media. Pair with a reach or pipeline outcome."),
    M("Speaking slots", "Marketing and Communications", "Awareness", "count", "A", ["accepted speaking slots"], "up", "leading",
      "Conference talks accepted, not talks merely submitted."),
    M("Community page visits", "Marketing and Communications", "Community", "count", "A", ["community page visits"], "up", "leading",
      "Visits to community pages in the period."),
    M("Community participation rate", "Marketing and Communications", "Community", "percent", "(A / B) * 100", ["customers who participated", "customers"], "up", "lagging",
      "Share of customers who did something in the community beyond a visit."),
    M("Experts contacted", "Marketing and Communications", "Community", "count", "A", ["experts contacted"], "up", "leading",
      "Experts contacted. Contact is an activity; publication is the result."),
    M("Blog posts published", "Marketing and Communications", "Content", "count", "A", ["posts published"], "up", "leading",
      "Posts published in the period."),
    M("Blog subscribers", "Marketing and Communications", "Content", "count", "A", ["subscribers at period end"], "up", "lagging",
      "People subscribed to the blog at period end."),
    M("Email click through rate", "Marketing and Communications", "Content", "percent", "(A / B) * 100", ["clicks", "emails delivered"], "up", "lagging",
      "Clicks divided by emails delivered."),
    M("Expert interviews", "Marketing and Communications", "Content", "count", "A", ["expert interviews published"], "up", "leading",
      "Interviews published, not conversations merely scheduled."),
    M("Newsletters published", "Marketing and Communications", "Content", "count", "A", ["newsletter issues published"], "up", "leading",
      "Issues actually sent. A task count; pair it with click-through or pipeline."),
    M("Product pages shipped", "Marketing and Communications", "Enablement", "count", "A", ["product pages updated"], "up", "leading",
      "Product pages updated to the agreed standard."),
    M("Sales enablement assets", "Marketing and Communications", "Enablement", "count", "A", ["enablement assets finished"], "up", "leading",
      "Datasheets, briefs, and packs finished for sales."),
    M("Marketing spend to gross profit", "Marketing and Communications", "Spend", "percent", "(A / B) * 100", ["marketing spend", "gross profit"], "corridor", "lagging",
      "Marketing spend as a share of gross profit.", notes=["Published agency rule of thumb: marketing spend around 5 to 10 percent of gross profit."]),
    # Online Presence
    M("Ecommerce conversion rate", "Online Presence", "Conversion", "percent", "(A / B) * 100", ["orders", "sessions"], "up", "lagging",
      "Orders divided by sessions. Read it once traffic is a known input; a falling rate on rising traffic may be a mix change, not a worse store."),
    M("Landing page conversion rate", "Online Presence", "Conversion", "percent", "(A / B) * 100", ["conversions", "landing page visits"], "up", "lagging",
      "Conversions divided by visits to the page."),
    M("Pages meeting speed budget", "Online Presence", "Conversion", "count", "A", ["pages inside the speed budget"], "up", "leading",
      "Pages whose measured speed is inside the agreed budget."),
    M("Referring domains", "Online Presence", "Traffic", "count", "A", ["new referring domains"], "up", "leading",
      "Distinct sites that newly link to the property in the period."),
    M("Website visitors", "Online Presence", "Traffic", "count", "A", ["sessions or users in the period"], "up", "leading",
      "People or sessions on the site. A leading input, not the outcome."),
    # Portfolio and Project Management
    M("Billed versus expected", "Portfolio and Project Management", "Delivery", "percent", "(A / B) * 100", ["amount billed", "amount expected"], "corridor", "lagging",
      "What was billed divided by what the plan said would be billed.", charts=("bullet-graph", "scatter-plot")),
    M("Estimated versus actual project time", "Portfolio and Project Management", "Delivery", "percent", "(A / B) * 100", ["estimated hours", "actual hours"], "corridor", "lagging",
      "Estimated hours divided by actual hours. Above 100 means the work took fewer hours than estimated.",
      charts=("bullet-graph", "scatter-plot"), extra_charts=["diverging-bar", "histogram", "data-table"]),
    M("Estimated versus actual project cost", "Portfolio and Project Management", "Delivery", "percent", "(A / B) * 100", ["estimated cost", "actual cost"], "corridor", "lagging",
      "Estimated cost divided by actual cost. Above 100 means the work cost less than estimated.",
      charts=("bullet-graph", "scatter-plot"), extra_charts=["diverging-bar", "histogram", "data-table"]),
    M("Project contribution margin", "Portfolio and Project Management", "Delivery", "percent", "((A - B) / A) * 100", ["project revenue", "direct cost"], "up", "lagging",
      "Share of project revenue left after direct delivery cost.", charts=("bullet-graph", "waterfall-chart"), extra_charts=["data-table"]),
    M("Lead time per project", "Portfolio and Project Management", "Delivery", "days", "A", ["calendar days from start to finish"], "down", "lagging",
      "Calendar time a project takes from start to finish."),
    # Professional Services
    M("Lead to client conversion rate", "Professional Services", "Business Development", "percent", "(A / B) * 100", ["clients won", "leads"], "up", "lagging",
      "Share of leads that become clients."),
    M("Client breakeven", "Professional Services", "Clients", "months", "A", ["months until client contribution turns positive"], "down", "lagging",
      "How long until the client covers the cost to acquire and serve them."),
    M("Client ROI", "Professional Services", "Clients", "percent", "(A / B) * 100", ["client profit", "cost to serve the client"], "up", "lagging",
      "Profit from the client divided by the cost to serve them."),
    M("Labor efficiency ratio", "Professional Services", "Delivery", "number", "A / B", ["gross profit", "labor cost"], "up", "lagging",
      "Gross profit earned per unit of labor cost."),
    M("Utilization rate", "Professional Services", "Delivery", "percent", "(A / B) * 100", ["billable hours", "available hours"], "corridor", "leading",
      "Billable hours divided by available hours. A corridor, not a maximum: too low and the firm is idle, too high and quality or people break."),
    M("Gross profit per head", "Professional Services", "Profitability", "currency", "A / B", ["gross profit", "fee earners"], "up", "lagging",
      "Gross profit per fee earner.", notes=[GP_HEAD]),
    M("Team cost to gross profit", "Professional Services", "Profitability", "percent", "(A / B) * 100", ["team cost", "gross profit"], "down", "lagging",
      "Team cost as a share of gross profit.", notes=["Published agency rule of thumb: team cost at most 60 percent of gross profit."]),
    # Sales and Customer Service
    M("Accounts with health score", "Sales and Customer Service", "Customers", "percent", "(A / B) * 100", ["accounts with a current health score", "active accounts"], "up", "leading",
      "Share of active accounts with a health score inside the freshness window."),
    M("At risk accounts contacted", "Sales and Customer Service", "Customers", "percent", "(A / B) * 100", ["flagged accounts contacted", "accounts flagged at risk"], "up", "leading",
      "Share of accounts flagged at risk that were contacted in the window."),
    M("Customer interviews", "Sales and Customer Service", "Customers", "count", "A", ["customer interviews completed"], "up", "leading",
      "Completed interviews with customers in the period. An activity count; pair it with an outcome such as retention or NPS."),
    M("Customer satisfaction score", "Sales and Customer Service", "Customers", "percent", "(A / B) * 100", ["satisfied responses", "survey responses"], "up", "lagging",
      "Share of survey responses at or above the satisfied threshold on the stated scale."),
    M("Net promoter score", "Sales and Customer Service", "Customers", "number", "A - B", ["percent promoters", "percent detractors"], "up", "lagging",
      "Percent of respondents who are promoters (9 or 10 on the 0 to 10 scale) minus percent who are detractors (0 to 6). Ranges from -100 to 100.",
      charts=("big-number", "diverging-stacked-bar")),
    M("Weekly active users", "Sales and Customer Service", "Customers", "percent", "(A / B) * 100", ["customers active in the week", "customers"], "up", "leading",
      "Share of customers who used the product in the week."),
    M("Expansion revenue", "Sales and Customer Service", "Expansion", "currency", "A", ["revenue from upsell and cross-sell"], "up", "lagging",
      "Revenue from existing customers buying more."),
    M("Upsell rate", "Sales and Customer Service", "Expansion", "percent", "(A / B) * 100", ["customers who bought more", "customers eligible"], "up", "lagging",
      "Share of eligible customers who expanded."),
    M("Marketplace liquidity", "Sales and Customer Service", "Marketplace", "percent", "(A / B) * 100", ["listings that sold in the period", "listings live in the period"], "up", "lagging",
      "Share of live listings that transact in the period. It says whether both sides of the market are meeting."),
    M("Partner events", "Sales and Customer Service", "Partners", "count", "A", ["partner events held"], "up", "leading",
      "Partner events held."),
    M("Partner webinars", "Sales and Customer Service", "Partners", "count", "A", ["partner webinars held"], "up", "leading",
      "Webinars held with or for partners."),
    M("Partner whitepapers", "Sales and Customer Service", "Partners", "count", "A", ["partner papers published"], "up", "leading",
      "Partner papers published."),
    M("Resellers onboarded", "Sales and Customer Service", "Partners", "count", "A", ["resellers who completed onboarding"], "up", "lagging",
      "Resellers who completed onboarding."),
    M("Average deal size", "Sales and Customer Service", "Pipeline", "currency", "A / B", ["closed-won revenue", "closed-won deals"], "up", "lagging",
      "Closed-won revenue divided by closed-won deals."),
    M("Closed won rate", "Sales and Customer Service", "Pipeline", "percent", "(A / B) * 100", ["deals won", "deals closed"], "up", "lagging",
      "Wins divided by decisions (won plus lost)."),
    M("Coaching sessions", "Sales and Customer Service", "Pipeline", "count", "A", ["coaching sessions held"], "up", "leading",
      "Coaching sessions held. Pair with a pipeline or win-rate outcome."),
    M("New accounts", "Sales and Customer Service", "Pipeline", "count", "A", ["new named accounts"], "up", "lagging",
      "Named accounts opened in the period."),
    M("Pipeline coverage", "Sales and Customer Service", "Pipeline", "number", "A / B", ["open pipeline", "remaining quota"], "corridor", "leading",
      "Open pipeline divided by the remaining quota."),
    M("Pipeline created", "Sales and Customer Service", "Pipeline", "currency", "A", ["new pipeline value"], "up", "leading",
      "Value of opportunities created in the period, on the stated stage rule."),
    M("Product demos", "Sales and Customer Service", "Pipeline", "count", "A", ["demos delivered"], "up", "leading",
      "Demos delivered, not demos scheduled."),
    M("Sales qualified leads", "Sales and Customer Service", "Pipeline", "count", "A", ["leads accepted by sales"], "up", "leading",
      "Leads sales accepted under the written qualification rule."),
    M("Customer churn rate", "Sales and Customer Service", "Retention", "percent", "(A / B) * 100", ["customers lost in the period", "customers at the start of the period"], "down", "lagging",
      "Share of starting customers lost during the period. Logo churn, not revenue churn, unless the name says revenue.", kind="kri",
      charts=("line-chart", "survival-curve")),
    M("Customer retention", "Sales and Customer Service", "Retention", "percent", "(A / B) * 100", ["customers retained", "customers at the start of the period"], "up", "lagging",
      "Share of starting customers still active at the end of the period.", charts=("bullet-graph", "survival-curve")),
    M("Monthly recurring revenue", "Sales and Customer Service", "Revenue", "currency", "A + B + C - D - E",
      ["MRR at the start of the month", "new MRR", "expansion MRR", "churned MRR", "contraction MRR"], "up", "lagging",
      "Contracted recurring revenue normalized to one month: the opening balance plus new and expansion MRR, minus churned and contraction MRR.",
      charts=("line-chart", "waterfall-chart")),
    M("Revenue", "Sales and Customer Service", "Revenue", "currency", "A", ["recognized revenue"], "up", "lagging",
      "Revenue recognized in the period on the stated basis."),
    M("Sales growth", "Sales and Customer Service", "Revenue", "percent", "((A - B) / B) * 100", ["revenue this period", "revenue in the comparison period"], "up", "lagging",
      "Change in revenue against the comparison period, as a percent of that period. Say the region and the comparison."),
    M("First response time", "Sales and Customer Service", "Support", "hours", "A", ["elapsed hours to first response"], "down", "lagging",
      "Elapsed time from ticket open to first response. State the percentile, not only the mean."),
    M("Resolution time", "Sales and Customer Service", "Support", "hours", "A", ["elapsed hours to resolution"], "down", "lagging",
      "Elapsed time from open to resolution. State the percentile, not only the mean."),
    M("Tickets resolved within 24 hours", "Sales and Customer Service", "Support", "percent", "(A / B) * 100", ["tickets resolved within 24 hours", "tickets resolved"], "up", "lagging",
      "Share of resolved tickets closed within 24 hours of opening."),
]

# (id, objective, context, level, function, audience role, key results)
# Key result: (statement, exact KPI name, target, cadence). Direction comes from the KPI.
NOTE_OKRS = [
    ("company-grow", "Grow our corporate global business", "internal", "company", "Management", "Executive",
     [("Hit the global sales target", "Revenue", "100 million currency units in the year", "year"),
      ("Grow EMEA sales versus last year", "Sales growth", "100 percent year over year in EMEA", "year"),
      ("Increase average deal size", "Average deal size", "30 percent above last year", "year"),
      ("Reduce annual churn", "Customer churn rate", "under 5 percent", "year")]),
    ("company-delight", "Delight our customers", "internal", "company", "Sales and Customer Service", "Executive",
     [("Interview customers each month", "Customer interviews", "20 interviews per month", "month"),
      ("Reach the customer NPS target", "Net promoter score", "the agreed NPS target on the 0 to 10 survey", "quarter"),
      ("Raise retention", "Customer retention", "98 percent", "quarter"),
      ("Raise weekly active use", "Weekly active users", "80 percent of customers active weekly", "week")]),
    ("company-culture", "Build a culture people want to stay in", "internal", "company", "Human Resources", "HR business partner",
     [("Run a weekly pulse", "Employee pulse score", "8 or higher", "week"),
      ("Hold a monthly town hall with open questions", "Town hall held", "1 per month", "month")]),
    ("mkt-mql", "Generate more marketing qualified leads", "internal", "function", "Marketing and Communications", "Marketing analytics",
     [("MQLs from email", "Marketing qualified leads", "150 from email", "quarter"),
      ("MQLs from paid search", "Marketing qualified leads", "100 from paid search", "quarter"),
      ("MQLs from organic search", "Marketing qualified leads", "50 from organic search", "quarter")]),
    ("mkt-cac", "Lower the cost of acquiring a customer", "internal", "function", "Marketing and Communications", "Marketing analytics",
     [("Reduce CAC", "Customer acquisition cost", "20 percent below the prior quarter", "quarter")]),
    ("mkt-abm", "Make account-based marketing a real source of revenue", "internal", "function", "Marketing and Communications", "Marketing analytics",
     [("Closed-won rate on ABM accounts", "Closed won rate", "20 percent of ABM decisions won in the quarter", "quarter")]),
    ("web-traffic", "Grow the site and the conversions on it", "client", "function", "Online Presence", "Marketing analytics",
     [("Grow visitors", "Website visitors", "7 percent more every month", "month"),
      ("Lift landing-page conversion", "Landing page conversion rate", "10 percent above the prior quarter", "quarter")]),
    ("ppc", "Keep paid search inside its efficiency limits", "client", "function", "Marketing and Communications", "Marketing analytics",
     [("MQLs from paid search", "Marketing qualified leads", "150", "quarter"),
      ("Cost per lead", "Cost per lead", "4 currency units or less", "month"),
      ("Click-through rate", "Click through rate", "2 percent or higher", "month")]),
    ("seo", "Earn relevant organic demand", "client", "function", "Online Presence", "Marketing analytics",
     [("New relevant referring domains", "Referring domains", "10", "quarter"),
      ("Landing pages meeting the speed budget", "Pages meeting speed budget", "the agreed template set", "quarter")]),
    ("newsletter", "Launch the monthly newsletter", "internal", "function", "Marketing and Communications", "Marketing analytics",
     [("Issues published", "Newsletters published", "3 this quarter, 1 per month", "quarter"),
      ("Newsletter click-through", "Email click through rate", "3 percent or higher", "month")]),
    ("blog", "Make the blog a subscriber channel", "internal", "function", "Marketing and Communications", "Marketing analytics",
     [("Posts published", "Blog posts published", "50 in the quarter", "quarter"),
      ("Expert interviews published", "Expert interviews", "5", "quarter"),
      ("Blog subscribers", "Blog subscribers", "5000", "quarter")]),
    ("pr", "Increase brand awareness through earned conversations", "internal", "function", "Marketing and Communications", "Executive",
     [("Media meetings", "Media meetings", "30 by end of quarter", "quarter"),
      ("Influencer meetings", "Influencer meetings", "15", "quarter"),
      ("Conference talks accepted", "Speaking slots", "2", "year")]),
    ("analysts", "Be present in the analyst conversation", "internal", "function", "Marketing and Communications", "Executive",
     [("Analyst briefings", "Analyst briefings", "2 in the quarter", "quarter"),
      ("Analysts hosted on webinars", "Analyst webinars", "2", "quarter")]),
    ("community", "Launch a customer community people actually use", "internal", "function", "Marketing and Communications", "Marketing analytics",
     [("Community visits", "Community page visits", "6000 visits", "quarter"),
      ("Customers participating", "Community participation rate", "30 percent of customers", "quarter")]),
    ("community-experts", "Bring recognized practitioners into the community", "internal", "function", "Marketing and Communications", "Marketing analytics",
     [("Experts contacted", "Experts contacted", "12", "quarter"),
      ("Interviews published", "Expert interviews", "the contacted set that agrees", "quarter")]),
    ("product-mkt", "Launch the product with the materials sales can use", "internal", "function", "Marketing and Communications", "Executive",
     [("Product pages updated", "Product pages shipped", "the agreed set", "quarter"),
      ("Datasheets and briefs finished", "Sales enablement assets", "datasheet, feature brief, and enablement pack", "quarter")]),
    ("partners", "Give partners a reason to learn the product", "internal", "function", "Sales and Customer Service", "Executive",
     [("Partner papers published", "Partner whitepapers", "5", "quarter"),
      ("Partner webinars", "Partner webinars", "7", "quarter"),
      ("Partner events", "Partner events", "5 cities", "quarter")]),
    ("sales-pipeline", "Keep a pipeline that can hit the number", "internal", "function", "Sales and Customer Service", "Executive",
     [("Pipeline created", "Pipeline created", "12 million currency units", "quarter"),
      ("Coverage", "Pipeline coverage", "between 3 and 5 times the remaining quota", "week"),
      ("Demos", "Product demos", "7 per week", "week")]),
    ("sales-hires", "Hire the sales roles the plan requires", "internal", "function", "Human Resources", "HR business partner",
     [("Account executives hired", "Account executives hired", "10", "quarter"),
      ("SDRs hired", "Sales development hires", "20", "quarter"),
      ("Interview-to-offer", "Interview to offer ratio", "between 3 and 5 interviews per offer", "month")]),
    ("sales-coach", "Coach the team every week", "internal", "team", "Sales and Customer Service", "Executive",
     [("Reps with a weekly coaching session", "Coaching sessions", "every rep, every week", "week")]),
    ("sales-region", "Grow the named region with local coverage", "internal", "team", "Sales and Customer Service", "Executive",
     [("New named accounts in the region", "New accounts", "50", "quarter"),
      ("Resellers onboarded", "Resellers onboarded", "10", "quarter")]),
    ("sdr-sql", "Pass sales-qualified leads the closers accept", "internal", "team", "Sales and Customer Service", "Data analytics",
     [("SQLs passed", "Sales qualified leads", "80", "quarter"),
      ("SDRs trained on the social motion", "SDRs trained", "5", "quarter")]),
    ("upsell", "Grow revenue from customers we already have", "internal", "function", "Sales and Customer Service", "Executive",
     [("Upsell and cross-sell revenue", "Expansion revenue", "40 percent above the prior period", "quarter"),
      ("Retention", "Customer retention", "98 percent", "quarter")]),
    ("cs", "See risk before the customer leaves", "internal", "function", "Sales and Customer Service", "Data analytics",
     [("Accounts with a health score", "Accounts with health score", "every active account", "week"),
      ("At-risk accounts contacted", "At risk accounts contacted", "every account flagged that week", "week")]),
    ("support", "Resolve support at the standard the customer was promised", "internal", "function", "Sales and Customer Service", "Executive",
     [("Tier-1 CSAT", "Customer satisfaction score", "90 percent or higher", "week"),
      ("Tier-1 first response", "First response time", "within 1 hour at the 90th percentile", "week"),
      ("Tier-2 resolved in a day", "Tickets resolved within 24 hours", "95 percent", "week")]),
    ("finance-close", "Close the books on the calendar we promised", "internal", "function", "Finance", "Executive",
     [("Days to close", "Days to close", "within 10 business days of quarter end", "quarter")]),
    ("finance-budget", "Finish the budget before the year needs it", "internal", "function", "Finance", "Executive",
     [("Function budgets reviewed", "Budgets reviewed", "every requesting function", "quarter")]),
    ("ops-it", "Keep internal systems available", "internal", "function", "Information Technology", "Development",
     [("Unplanned downtime", "Unplanned downtime", "none in the quarter", "quarter"),
      ("Restore test passed", "Restore tests passed", "the agreed backup test", "quarter")]),
    ("eng-quality", "Ship the release without a critical regression", "internal", "function", "Information Technology", "Development",
     [("Critical bugs after release", "Critical defects", "at most 1", "quarter"),
      ("Regressions", "Regressions", "zero", "quarter")]),
    ("product-discovery", "Learn from the people who would use the product", "internal", "function", "Management", "Researcher",
     [("Discovery interviews", "Customer interviews", "30", "quarter"),
      ("Usability score on the prototype", "Usability score", "above 8 out of 10", "quarter")]),
    ("agency-leads", "Keep the agency's own lead flow ahead of the work it needs", "internal", "company", "Professional Services", "Executive",
     [("Lead to client conversion", "Lead to client conversion rate", "the quarterly target", "month"),
      ("Wins with a known source", "Wins by lead source", "every win coded to a source", "month")]),
    ("agency-delivery", "Deliver projects inside the hours and cost we quoted", "project", "team", "Portfolio and Project Management", "Executive",
     [("Hours versus estimate", "Estimated versus actual project time", "inside the agreed band, for example 100 to 110 (estimate over actual)", "project"),
      ("Cost versus estimate", "Estimated versus actual project cost", "inside the agreed band, for example 100 to 110 (estimate over actual)", "project"),
      ("Contribution margin", "Project contribution margin", "at or above the quoted margin", "project")]),
    ("agency-client", "Show the client the outcome we agreed, in their numbers", "client", "function", "Professional Services", "Client",
     [("Client ROI", "Client ROI", "above the agreed hurdle", "quarter"),
      ("Client breakeven", "Client breakeven", "reached inside the agreed window", "quarter")]),
]

# (id, business model, KPI name, why)
OMTM = [
    ("agency", "Agency", "Project contribution margin",
     "An agency principal steers on whether delivery earned the profit that was quoted."),
    ("saas", "SaaS", "Monthly recurring revenue",
     "A subscription business steers on recurring revenue, with customer churn rate beside it as a KRI."),
    ("ecommerce", "Ecommerce", "Ecommerce conversion rate",
     "A store steers on conversion once traffic is a known input, not on traffic alone."),
    ("marketplace", "Marketplace", "Marketplace liquidity",
     "A marketplace steers on whether both sides of the market are transacting."),
    ("professional-services", "Professional services", "Utilization rate",
     "Utilization is a corridor: too little and the firm is idle, too much and quality or people break."),
]

# Scenario cards. The sequence follows the scenario and practice chapters of The Big Book of
# Dashboards (Wexler, Shaffer, Cotgreave; Wiley, 2017); questions and guidance are original.
PATTERNS = [
    (2, "Course metrics", "Is the cohort learning, and where is the drop?", ["line-chart", "bar-chart"], "A small set of rates over the term, not a gallery."),
    (3, "Individual versus peers", "Where does this person sit among peers?", ["dot-plot", "box-plot"], "Show the distribution. A rank without the spread flatters or shames."),
    (4, "What-if", "What happens to the result if one driver moves?", ["kpi-tree", "waterfall-chart"], "The tree is the model. The waterfall is the result of one change."),
    (5, "Executive sales", "Are we on pace, and which segment explains the gap?", ["line-chart", "bar-chart", "waterfall-chart"], "Score, trend, then one breakdown."),
    (6, "Now versus then", "What changed rank since the comparison period?", ["slope-chart", "bump-chart"], "Two times. Not a spaghetti of every month."),
    (7, "Pace to goal", "Will we land on the target if the recent rate holds?", ["line-chart", "bullet-graph"], "Path plus target. A gauge throws the path away."),
    (8, "Several KPIs at once", "Are the few key results healthy together?", ["ibcs-variance-table", "bullet-graph"], "A scorecard, not forty tiles."),
    (9, "Operations monitoring", "Is the process inside its corridor right now?", ["run-chart", "control-chart"], "Technical audience may use the control chart. The shift lead may only need the run and the exceptions."),
    (10, "YTD and year ago", "How does this year compare with last year, to date?", ["line-chart", "diverging-bar"], "Two explicit series. Do not make the reader remember."),
    (11, "Player performance", "Who is extreme, and on which measure?", ["scatter-plot", "bar-chart"], "Analytics surface can be the scatter. Communication can be the sorted bar."),
    (12, "Match performance", "What changed during the event?", ["timeline", "bar-chart"], "Time order of events, then the totals."),
    (13, "Web analytics", "Where does traffic become a lead?", ["line-chart", "funnel-chart"], "Funnel only if the steps are a real sequence."),
    (14, "Patient history", "What happened to this person over time?", ["timeline", "line-chart"], "One patient is not a population average."),
    (15, "Hotel operations", "Are occupancy, rate, and service inside plan tonight?", ["bullet-graph", "line-chart"], "Tonight's exceptions, then the month."),
    (16, "Sentiment distribution", "Is the average hiding an angry tail?", ["diverging-stacked-bar", "histogram"], "Show the distribution. The mean is not the story."),
    (17, "NPS with the distribution", "What sits behind the single NPS figure?", ["diverging-stacked-bar", "big-number"], "The score for the executive, the distribution for the researcher."),
    (18, "Server monitoring", "Which process is away from its corridor?", ["run-chart", "horizon-chart"], "Horizon is a notebook or an operator wall, not a board slide."),
    (19, "Index comparison", "How does a price compare across places?", ["bar-chart", "choropleth-map"], "Say the base of the index."),
    (20, "Complaints", "What do people complain about, and is it growing?", ["pareto-chart", "line-chart"], "Pareto of reasons, trend of volume."),
    (21, "Utilization versus potential", "Where is capacity unused?", ["bullet-graph", "bar-chart"], "Utilization is a corridor."),
    (22, "Rank and magnitude", "Who is first, and by how much?", ["horizontal-bar-chart", "lollipop-chart"], "Sort by the value."),
    (23, "Many measures, many dimensions", "Which slice is different on more than one measure?", ["ibcs-variance-table", "heat-map"], "A table with marks. Not a radar."),
    (24, "Churn", "Who left, and was it logos or revenue?", ["waterfall-chart", "line-chart"], "Do not mix the two definitions."),
    (25, "Actual versus potential", "How far is actual from the ceiling we believe?", ["bullet-graph", "diverging-bar"], "State what potential means."),
    (26, "Productivity", "Output per person, with the mix visible?", ["bar-chart", "scatter-plot"], "Scatter for the analyst. Bar of the outliers for the manager."),
    (27, "Executive telecom", "Are growth, service, and network risk all visible?", ["line-chart", "big-number", "data-table"], "Put a KRI beside the growth KPI, not on another page."),
    (28, "Economy at a glance", "What moved in the handful of macro series?", ["small-multiples", "sparkline"], "Small multiples, shared time."),
    (29, "Call center", "Are we answering, and is the queue aging?", ["run-chart", "bar-chart"], "Service level and aging, not a gauge."),
    (30, "Personal scope", "Does this page show the viewer's own work?", ["data-table", "big-number"], "Impersonal walls do not get action."),
    (31, "Time as time", "Is time an axis?", ["line-chart"], "Do not encode time only as color or a pie slice."),
    (32, "No dead end", "Can the reader reach the entity they must change?", ["bar-chart", "data-table"], "Score without a detail zone is a dead end."),
    (33, "Not only red and green", "Can the variance be read without color?", ["diverging-bar"], "Sign and position carry the message."),
    (34, "Not a pie", "Is a part-to-whole being shown with angles?", ["stacked-bar-chart"], "Bars or a table of shares."),
    (35, "Not a cloud of bubbles", "Is area pretending to be a precise magnitude?", ["scatter-plot", "bar-chart"], "Bubbles only when a third variable is real and the audience is analytical."),
    (36, "Unknown data", "Do we know the shape before we pick the chart?", ["histogram", "scatter-plot"], "Look first. A dashboard template is not a finding."),
]
BIG_BOOK = "The Big Book of Dashboards (Steve Wexler, Jeffrey Shaffer, Andy Cotgreave; Wiley, 2017)"


def charts_for(m: M) -> tuple[str, str]:
    """(communication, analysis). Rates and corridors read against a band; totals read as a trend."""
    if m.charts:
        return m.charts
    comm = "bullet-graph" if m.direction == "corridor" or m.unit in {"percent", "number"} else "line-chart"
    if m.unit in {"days", "hours", "months"} or m.unit in {"percent", "number"} and "/" in m.formula:
        analysis = "histogram"  # the spread across entities or tickets, not only the mean
    else:
        analysis = "bar-chart"  # the breakdown by entity
    return comm, analysis


def kpi_record(m: M) -> dict:
    comm, analysis = charts_for(m)
    related = list(dict.fromkeys([comm, analysis] + m.extra_charts))
    level = "strategic" if m.function in {"Finance", "Management"} and m.timing == "lagging" else (
        "operational" if m.timing == "leading" and m.unit == "count" else "tactical")
    return {
        "id": f"kpi.{slug(m.function)}.{slug(m.name)}",
        "name": m.name,
        "measure_kind": m.kind,
        "function": m.function,
        "area": m.area,
        "unit": m.unit,
        "definition": m.definition,
        "formula": m.formula,
        "formula_inputs": ["metric." + slug(i) for i in m.inputs],
        "input_names": m.inputs,
        "direction": m.direction,
        "leading_lagging": m.timing,
        "level": level,
        "audience_roles": ROLES_BY_FUNCTION[m.function],
        "questions": [
            f"Is {m.name} on the desired side of its target for this period?" if m.direction != "corridor"
            else f"Is {m.name} inside its corridor for this period?",
            f"Which input moved {m.name}?",
        ],
        "related_charts": related,
        "analysis_surface": "notebook",
        "analysis_chart": analysis,
        "communication_surface": "dashboard",
        "communication_chart": comm,
        "dashboard": f"dash.{slug(m.function)}.{slug(m.area)}",
        "target_notes": m.notes,
        "provenance": "authored",
    }


def build_catalog() -> tuple[list[dict], list[dict]]:
    kpis = [kpi_record(m) for m in CORE]
    errors = []
    seen: dict[str, str] = {}
    for k, m in zip(kpis, CORE):
        if k["id"] in seen:
            errors.append(f"duplicate KPI id {k['id']} ({seen[k['id']]} / {m.name})")
        seen[k["id"]] = m.name
        if m.unit not in UNITS:
            errors.append(f"{k['id']}: unit {m.unit!r} not in {sorted(UNITS)}")
        if m.direction not in DIRECTIONS:
            errors.append(f"{k['id']}: direction {m.direction!r}")
        letters = set(re.findall(r"\b[A-G]\b", m.formula))
        if letters != set("ABCDEFG"[: len(m.inputs)]):
            errors.append(f"{k['id']}: formula {m.formula!r} does not use exactly {len(m.inputs)} inputs")
    if errors:
        raise SystemExit("\n".join(errors))
    metrics: dict[str, dict] = {}
    for k in kpis:
        for mid, name in zip(k["formula_inputs"], k["input_names"]):
            row = metrics.setdefault(mid, {"id": mid, "name": name, "used_by": []})
            row["used_by"].append(k["id"])
    return kpis, sorted(metrics.values(), key=lambda r: r["id"])


def kpi_block(k: dict) -> str:
    inputs = "\n".join(f"  - {letter} = `{mid}` ({name})" for letter, mid, name in zip("ABCDEFG", k["formula_inputs"], k["input_names"]))
    notes = "".join(f"\n- Target note: {n}" for n in k["target_notes"])
    return (
        f"### {k['name']}\n\n"
        f"- id: `{k['id']}`\n"
        f"- kind: {k['measure_kind']}; unit: {k['unit']}; direction: {k['direction']}; timing: {k['leading_lagging']}; level: {k['level']}\n"
        f"- formula: `{k['formula']}`\n{inputs}\n"
        f"- communication chart: `{k['communication_chart']}`; analysis chart: `{k['analysis_chart']}` (notebook)\n"
        f"- dashboard: `{k['dashboard']}`; readers: {', '.join(k['audience_roles'])}"
        f"{notes}\n\n{k['definition']}\n"
    )


def render(kpis: list[dict], metrics: list[dict], chart_stems: set[str]) -> dict[Path, str]:
    out: dict[Path, str] = {}
    by_name = {k["name"]: k for k in kpis}
    for k in kpis:
        for c in k["related_charts"]:
            if c not in chart_stems:
                raise SystemExit(f"{k['id']}: chart {c!r} has no card under library/CHARTS/")
    cat = LIB / "KPIS" / "_catalog"
    out[cat / "kpis.jsonl"] = "".join(json.dumps(k, ensure_ascii=False) + "\n" for k in kpis)
    out[cat / "metrics.jsonl"] = "".join(json.dumps(m, ensure_ascii=False) + "\n" for m in metrics)

    by_fn: dict[str, list[dict]] = defaultdict(list)
    for k in kpis:
        by_fn[k["function"]].append(k)
    index = ["# KPIs", "", f"{len(kpis)} authored measures. {GENERATED}", "",
             "Each card has a formula whose inputs are named metrics (`_catalog/metrics.jsonl`), a direction, a leading or lagging label, "
             "and two charts: the communication chart for a dashboard, report, or story, and the analysis chart for a notebook.", "",
             "Machine-readable: `_catalog/kpis.jsonl` (one KPI per line) and `_catalog/metrics.jsonl` (each metric with the KPIs that use it).", ""]
    for fn in sorted(by_fn):
        page = LIB / "KPIS" / f"{slug(fn)}.md"
        lines = [f"# {fn}", "", GENERATED, ""]
        areas: dict[str, list[dict]] = defaultdict(list)
        for k in by_fn[fn]:
            areas[k["area"]].append(k)
        for area in sorted(areas):
            lines += [f"## {area}", ""]
            lines += [kpi_block(k) for k in sorted(areas[area], key=lambda k: k["name"].lower())]
        out[page] = "\n".join(lines)
        index.append(f"- [{fn}]({slug(fn)}.md): {len(by_fn[fn])}")
    out[LIB / "KPIS" / "index.md"] = "\n".join(index)

    kris = sorted((k for k in kpis if k["measure_kind"] == "kri"), key=lambda k: k["id"])
    out[LIB / "KRIS" / "index.md"] = "\n".join(
        ["# Key risk indicators", "", f"{len(kris)} measures use `measure_kind: kri`. They track exposure, not success. {GENERATED}", ""]
        + [f"- `{k['id']}` {k['name']} ({k['direction']}, {k['unit']}). Communication `{k['communication_chart']}`." for k in kris])

    okr_index = ["# OKRs", "", f"Authored objectives. Every key result binds to one KPI id. {GENERATED}", ""]
    for oid, objective, ctx, level, function, role, krs in NOTE_OKRS:
        if role not in ROLE_TOLERANCE:
            raise SystemExit(f"okr {oid}: audience {role!r} is not a defined role")
        lines = ["---", f"id: okr.note.{oid}", "type: okr", f"context: {ctx}", f"level: {level}", f"function: {function}",
                 f"audience: {role}", "---", "", f"# {objective}", "", "Key results:", ""]
        for statement, kname, target, cadence in krs:
            k = by_name.get(kname)
            if k is None:
                raise SystemExit(f"okr {oid}: key result {statement!r} names {kname!r}, which is not a KPI in CORE")
            lines.append(f"- {statement}. KPI `{k['id']}`. Target: {target}. Direction: {k['direction']}. Cadence: {cadence}.")
        lines += ["", "Anti-pattern: a key result that is only a task, or a target with no KPI id.", ""]
        out[LIB / "OKRS" / "note" / f"{oid}.md"] = "\n".join(lines)
        okr_index.append(f"- {level} / {role} / {ctx}: [{objective}](note/{oid}.md)")
    out[LIB / "OKRS" / "index.md"] = "\n".join(okr_index)

    omtm_index = ["# OMTM", "", f"One metric that matters per business model. {GENERATED}", ""]
    for oid, model, kname, why in OMTM:
        k = by_name[kname]
        out[LIB / "OMTM" / f"{oid}.md"] = (
            f"---\nid: omtm.{oid}\ntype: omtm\nmodel: {model}\nkpi: {k['id']}\n---\n\n# {model}\n\n{why}\n\n"
            f"KPI: `{k['id']}` ({k['name']}, {k['unit']}, direction {k['direction']}). Formula `{k['formula']}`.\n\n"
            f"Communication surface: `{k['communication_chart']}` on a dashboard or board pack. "
            f"Analysis surface: `{k['analysis_chart']}` in a notebook.\n"
        )
        omtm_index.append(f"- [{model}]({oid}.md): `{k['id']}`")
    out[LIB / "OMTM" / "index.md"] = "\n".join(omtm_index)

    dash_index = ["# Dashboards", "", GENERATED, "",
                  "One specification per (function, area) of the authored KPIs, and scenario cards under `patterns/`. "
                  "A dashboard is one communication surface. Technical readers keep the analysis chart in a notebook.", ""]
    groups: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for k in kpis:
        groups[(k["function"], k["area"])].append(k)
    for (fn, area), items in sorted(groups.items()):
        items = sorted(items, key=lambda k: k["name"].lower())
        did = f"dash.{slug(fn)}.{slug(area)}"
        roles = list(dict.fromkeys(r for k in items for r in k["audience_roles"]))
        lines = [
            "---", f"id: {did}", "type: dashboard", "status: specification", f"function: {fn}", f"area: {area}",
            f"audience_roles: [{', '.join(roles)}]", "---", "", f"# {fn} / {area}", "",
            "A specification, not a claim that a live dashboard exists.", "",
            "## Questions", "",
            f"- Are the {area.lower()} measures on the right side of their targets or inside their corridors?",
            "- Which input moved, and is that a signal or a tail?", "",
            "## Zones (communication)", "",
            "| Zone | What goes here |", "|---|---|",
            "| Score | `big-number` or `bullet-graph` against target for the lead KPI |",
            "| Trend | `line-chart` of that KPI |",
            "| Breakdown | Sorted `bar-chart` of the entities |",
            "| Variance | `waterfall-chart` or `diverging-bar` against plan |",
            "| Detail | `data-table` of the rows a person can act on |", "",
            "## KPIs", "",
        ]
        lines += [f"- `{k['id']}` {k['name']} ({k['measure_kind']}). Communication `{k['communication_chart']}`. Analysis `{k['analysis_chart']}`." for k in items]
        lines.append("")
        out[LIB / "DASHBOARDS" / slug(fn) / f"{slug(area)}.md"] = "\n".join(lines)
        dash_index.append(f"- [{fn} / {area}]({slug(fn)}/{slug(area)}.md): `{did}`")
    dash_index += ["", "## Patterns", "", f"Scenario and practice cards in the chapter order of {BIG_BOOK}. Questions and guidance are original.", ""]
    for num, title, question, charts, why in PATTERNS:
        for c in charts:
            if c not in chart_stems:
                raise SystemExit(f"pattern {num}: chart {c!r} has no card")
        name = f"{num:02d}-{slug(title)}.md"
        kind = "practice" if num >= 30 else "scenario"
        out[LIB / "DASHBOARDS" / "patterns" / name] = (
            f"---\nid: pattern.{num}\ntype: {kind}\n---\n\n# {num}. {title}\n\nQuestion: {question}\n\n"
            f"Charts: {', '.join(f'`{c}`' for c in charts)}.\n\nWhy: {why}\n\n"
            f"Chapter reference: {BIG_BOOK}, chapter {num}. The card is a rule, not the chapter.\n\n"
            "Audience split: the analytical form may be a notebook plot. The communication form is the simpler chart in the list.\n"
        )
        dash_index.append(f"- [{num}. {title}](patterns/{name})")
    out[LIB / "DASHBOARDS" / "index.md"] = "\n".join(dash_index)
    return {p: t if t.endswith("\n") else t + "\n" for p, t in out.items()}


def patch_chart_kpis(kpis: list[dict]) -> dict[Path, str]:
    by_chart: dict[str, list[str]] = defaultdict(list)
    for k in kpis:
        for c in k["related_charts"]:
            by_chart[c].append(k["id"])
    out = {}
    for path in sorted(p for p in CHARTS.rglob("*.md") if not p.name.startswith(".")):
        text = path.read_text(encoding="utf-8")
        ids = sorted(by_chart.get(path.stem, []))
        new = re.sub(r"(?m)^related_kpis:.*$", "related_kpis: [" + ", ".join(ids) + "]", text, count=1)
        if new != text:
            out[path] = new
    return out


def owned_files() -> set[Path]:
    """Files this script owns today; anything here that render() no longer produces is stale."""
    owned = set()
    for sub in ("KPIS", "KRIS", "OKRS", "OMTM", "DASHBOARDS"):
        owned |= {p for p in (LIB / sub).rglob("*") if p.is_file()}
    return owned


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="write nothing; exit 1 if any file would change")
    args = ap.parse_args()
    kpis, metrics = build_catalog()
    stems = {p.stem for p in CHARTS.rglob("*.md") if not p.name.startswith(".")}
    files = render(kpis, metrics, stems)
    files.update(patch_chart_kpis(kpis))
    stale = sorted(owned_files() - set(files))
    changed = [p for p, t in files.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
    if not args.check:
        for p in changed:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(files[p], encoding="utf-8", newline="\n")
        for p in stale:
            p.unlink()
        for d in sorted({p.parent for p in stale}, key=lambda d: -len(d.parts)):
            while d != LIB and d.exists() and not any(d.iterdir()):
                d.rmdir()
                d = d.parent
    verb = "would change" if args.check else "wrote"
    for p in sorted(changed):
        print(f"{verb}: {p.relative_to(REPO).as_posix()}")
    for p in stale:
        print(f"{'would remove' if args.check else 'removed'}: {p.relative_to(REPO).as_posix()}")
    print(f"kpis={len(kpis)} kris={sum(k['measure_kind'] == 'kri' for k in kpis)} metrics={len(metrics)} "
          f"changed={len(changed)} stale={len(stale)}")
    return 1 if args.check and (changed or stale) else 0


if __name__ == "__main__":
    sys.exit(main())
